services:
    db:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB_NAME}
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    api:
        restart: always
        build: .
        depends_on:
            wait-for-db:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
        ports:
            - 8000:8000

    nginx:
        image: nginx:alpine
        restart: always
        container_name: fastapi_nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - api

    wait-for-db:
        image: atkrad/wait4x
        depends_on:
            - db
        command: tcp db:5432 -t 30s -i 250ms
volumes:
    postgres_data:
