version: '3'
services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    api:
        build: .
        depends_on:
            - db
        env_file:
            - .env
        environment:
            DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
        ports:
            - 8000:8000
volumes:
    postgres_data:
