services:
    db:
        image: postgres:17
        restart: always
        container_name: postgres_db
        environment:
            POSTGRES_DB: ${POSTGRES_DB_NAME}
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    redis:
        image: redis:7
        restart: always
        container_name: redis_db
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    api:
        restart: always
        container_name: fast_api
        build: .
        depends_on:
            - db
            - redis
        env_file:
            - .env
        environment:
            DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
        ports:
            - 8000:8000

    nginx:
        image: nginx:alpine
        restart: always
        container_name: nginx_revers_proxy
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
volumes:
    postgres_data:
    redis_data:
